version: '3.8'

services:
  api:
    image: devopshub-api:v1
    container_name: devopshub-backend
    build: . 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - devopshub-network

networks:
  devopshub-network:
    external: true